### ISSUE TITLE
Can't get it to work in Godot 3.5

### ISSUE THREAD

**Issue by strellydev** [nklbdev/godot-enchanced-tile-map-editor#36]
Hello, I tried the plugin out but I can't get it to work, I enabled the plugin but whenever I select a tilemap in my scene tree it shows a bunch of errors in the console, I'll add a screenshot so you can see them.

![ErrorsTilePlugin](https://github.com/nklbdev/godot-enchanced-tile-map-editor/assets/113683950/a17cd690-f4c9-4d9c-9c30-7b5a3a454299)

Note that the "invalid get index pressed on nil" errors happen when dragging the cursor along the scene viewer, and the ones before those happen when selecting or unselecting a tilemap on the scene tree.

And when I open the project it says this:

![ErrorsTilePlugin2](https://github.com/nklbdev/godot-enchanced-tile-map-editor/assets/113683950/d286891f-d83c-49d9-a11b-76baf579bd6c)

What do you think could be the problem?

Thanks.

**Comment by nklbdev** [comment]
Thanks for the report, @strellydev! Probably something has been changed in recent updates to version 3.5, and the editor cannot find some of Godot's internal objects. He needs this in order to integrate in instead of the regular editor.

I'll try to debug it on the latest release of Godot 3.5 in the next day or two.

**Comment by nklbdev** [comment]
It looks like it can't find the CanvasItemEditor in the EditorViewport node. But this problem doesn't reproduce on my machine.
Please provide the exact version of your Godot engine and the hash of the commit you got the tile map editor from.

**Comment by strellydev** [comment]
Hi, thanks for the quick answer, the Godot version is v3.5.stable.official [991bb6ac7] and the commit for the plugin is #5fcf557, which should be the latest one, I just downloaded it today from the main page.

**Comment by strellydev** [comment]
With 3.5.2 (the latest you can download from godotengine.org) the Tile Map tab appears, but it still doesn't work, with new errors appearning. Here's a screenshot.

![ErrorsTilePlugin3](https://github.com/nklbdev/godot-enchanced-tile-map-editor/assets/113683950/a334cc46-fd5e-422b-9548-8ba6be75a216)

**Comment by nklbdev** [comment]
I figured out what the problem is. In the plugin settings, the parameter "palette_zoom_step_factor" is set to 0.
(Project Settings -> General -> Enchanced Tile Map Editor -> Palette Zoom Step Factor -> float value where 1.0 is for no zooming)

Godot sometimes incorrectly shows the location of the error. If a class has a parent class and the error occurred in it, it will show the script path of the child class, not the parent class. And the line number will be for the parent class.

I made a hotfix that will prevent zero from reaching the division operation, but please set the scaling factor to whatever you feel comfortable with.

**Comment by ghost** [comment]
The setting wasn't set to 0 but I downloaded the hotfix and it worked fine, thank you!
